# Generated by Django 2.2.5 on 2020-01-01 12:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='question',
            table='Question',
        ),
    ]
