# Generated by Django 2.2.5 on 2020-01-24 04:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_auto_20200112_0130'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='course_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='lecture',
            name='lecture_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
