# Generated by Django 2.2.5 on 2020-06-14 05:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20200124_1022'),
    ]

    operations = [
        migrations.CreateModel(
            name='Examination',
            fields=[
                ('examination_id', models.AutoField(primary_key=True, serialize=False)),
                ('aggregate', models.IntegerField(null=True)),
                ('resultstatus', models.CharField(max_length=10, null=True)),
                ('course_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Course')),
                ('student_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'Examination',
            },
        ),
    ]
