# Generated by Django 2.2.5 on 2020-06-14 05:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_examination'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='examination',
            unique_together={('student_id', 'course_id')},
        ),
    ]
