# Generated by Django 2.2.5 on 2020-06-18 15:02

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20200614_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='examination',
            name='completiondate',
            field=models.DateField(default=datetime.date.today),
        ),
    ]
